// memory/vue/v1/src/App.vue
<template>
  <div class="container">
    <h1>Memory Game</h1>
    <div class="board">
      <div
        v-for="(tile, idx) in tiles"
        :key="idx"
        class="tile"
        :class="{ flipped: tile.flipped || tile.matched }"
        @click="flipTile(idx)"
      >
        <span v-if="tile.flipped || tile.matched">{{ tile.letter }}</span>
        <span v-else>?</span>
      </div>
    </div>
    <div class="info">
      <button @click="resetGame">Restart</button>
      <p>Moves: {{ moves }}</p>
      <p v-if="matchedCount === tiles.length">🎉 You won! 🎉</p>
    </div>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {
      letters: ["A", "B", "C", "D", "E", "F", "G", "H"],
      tiles: [],
      flippedIndices: [],
      moves: 0,
    };
  },
  computed: {
    matchedCount() {
      return this.tiles.filter((t) => t.matched).length;
    },
  },
  created() {
    this.resetGame();
  },
  methods: {
    shuffle(array) {
      for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
      }
      return array;
    },
    resetGame() {
      const pairs = [...this.letters, ...this.letters];
      const shuffled = this.shuffle(pairs).map((letter) => ({
        letter,
        flipped: false,
        matched: false,
      }));
      this.tiles = shuffled;
      this.flippedIndices = [];
      this.moves = 0;
    },
    flipTile(idx) {
      if (
        this.tiles[idx].flipped ||
        this.tiles[idx].matched ||
        this.flippedIndices.length === 2
      )
        return;

      this.tiles[idx].flipped = true;
      this.flippedIndices.push(idx);

      if (this.flippedIndices.length === 2) {
        this.moves++;
        const [first, second] = this.flippedIndices;
        if (this.tiles[first].letter === this.tiles[second].letter) {
          // Match!
          this.tiles[first].matched = true;
          this.tiles[second].matched = true;
          this.flippedIndices = [];
        } else {
          // Not a match
          setTimeout(() => {
            this.tiles[first].flipped = false;
            this.tiles[second].flipped = false;
            this.flippedIndices = [];
          }, 900);
        }
      }
    },
  },
};
</script>

<style scoped>
.container {
  max-width: 400px;
  margin: 2rem auto;
  text-align: center;
  font-family: Arial, sans-serif;
}
.board {
  display: grid;
  grid-template-columns: repeat(4, 60px);
  grid-gap: 12px;
  justify-content: center;
  margin-bottom: 1.5rem;
}
.tile {
  width: 60px;
  height: 80px;
  background: #eee;
  border: 2px solid #bbb;
  border-radius: 7px;
  font-size: 2rem;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  user-select: none;
  transition: background 0.25s, border 0.25s;
}
.tile.flipped,
.tile.matched {
  background: #6cf;
  border-color: #269;
  color: #fff;
  cursor: default;
}
.info {
  margin-top: 1rem;
}
button {
  padding: 0.4rem 1rem;
  background: #269;
  color: #fff;
  border: none;
  border-radius: 5px;
  font-weight: bold;
  cursor: pointer;
}
button:hover {
  background: #37b;
}
</style>

// memory/react/v2/App.js
import { StatusBar } from 'expo-status-bar';
import { StyleSheet, Text, View, TouchableOpacity } from 'react-native';
import { useState, useEffect } from 'react';

export default function App() {
  const letters = ["A", "B", "C", "D", "E", "F", "G", "H"];
  const [tiles, setTiles] = useState([]);
  const [flippedIndices, setFlippedIndices] = useState([]);
  const [moves, setMoves] = useState(0);

  const shuffle = (array) => {
    const arr = [...array];
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  };

  const resetGame = () => {
    const pairs = [...letters, ...letters];
    const shuffled = shuffle(pairs).map((letter) => ({
      letter,
      flipped: false,
      matched: false,
    }));
    setTiles(shuffled);
    setFlippedIndices([]);
    setMoves(0);
  };

  useEffect(() => {
    resetGame();
  }, []);

  useEffect(() => {
    if (flippedIndices.length === 2) {
      setMoves(moves + 1);
      const [first, second] = flippedIndices;

      if (tiles[first].letter === tiles[second].letter) {
        // Match!
        const newTiles = [...tiles];
        newTiles[first].matched = true;
        newTiles[second].matched = true;
        setTiles(newTiles);
        setFlippedIndices([]);
      } else {
        // Not a match
        setTimeout(() => {
          const newTiles = [...tiles];
          newTiles[first].flipped = false;
          newTiles[second].flipped = false;
          setTiles(newTiles);
          setFlippedIndices([]);
        }, 900);
      }
    }
  }, [flippedIndices]);

  const flipTile = (idx) => {
    if (tiles[idx].flipped || tiles[idx].matched || flippedIndices.length === 2) {
      return;
    }

    const newTiles = [...tiles];
    newTiles[idx].flipped = true;
    setTiles(newTiles);
    setFlippedIndices([...flippedIndices, idx]);
  };

  const matchedCount = tiles.filter((t) => t.matched).length;

  return (
    <View style={styles.container}>
      <StatusBar style="auto" />
      <Text style={styles.title}>Memory Game</Text>

      <View style={styles.board}>
        {tiles.map((tile, idx) => (
          <TouchableOpacity
            key={idx}
            style={[
              styles.tile,
              (tile.flipped || tile.matched) && styles.tileFlipped
            ]}
            onPress={() => flipTile(idx)}
            activeOpacity={0.7}
          >
            <Text style={styles.tileText}>
              {tile.flipped || tile.matched ? tile.letter : '?'}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <View style={styles.info}>
        <TouchableOpacity style={styles.button} onPress={resetGame}>
          <Text style={styles.buttonText}>Restart</Text>
        </TouchableOpacity>
        <Text style={styles.movesText}>Moves: {moves}</Text>
        {matchedCount === tiles.length && tiles.length > 0 && (
          <Text style={styles.winText}>🎉 You won! 🎉</Text>
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    marginBottom: 30,
  },
  board: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: 320,
    justifyContent: 'center',
    marginBottom: 30,
  },
  tile: {
    width: 60,
    height: 80,
    backgroundColor: '#eee',
    borderWidth: 2,
    borderColor: '#bbb',
    borderRadius: 7,
    margin: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tileFlipped: {
    backgroundColor: '#6cf',
    borderColor: '#269',
  },
  tileText: {
    fontSize: 32,
    color: '#000',
  },
  info: {
    alignItems: 'center',
  },
  button: {
    backgroundColor: '#269',
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 5,
    marginBottom: 15,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  movesText: {
    fontSize: 18,
    marginBottom: 10,
  },
  winText: {
    fontSize: 20,
    fontWeight: 'bold',
    marginTop: 10,
  },
});
